channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - geopandas
  - ipyleaflet
  - matplotlib
  - notebook
  - pdal
  - pip
  - python-pdal
  - pyproj
  - requests
  - rioxarray
  - entwine
  - nodejs
  - numpy=1.26.4
  - pip:
    - ultralytics
    - rvt-py
    - laspy[lasrs,laszip]
    - fiona
    # - m2-base
    # - pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cpu
